version: '2.2'
services:
  redis:
    image: redis:5.0-alpine
    restart: always
    volumes:
      - redis:/data
      - logs:/var/log
    networks:
      - redis
    environment:
      - LOG_NAME=redis
  producer:
    build:
      context: ./src
      dockerfile: ../producer.dockerfile
    entrypoint: 'python ./producer/main.py'
    volumes:
      - logs:/var/log
    networks:
      - redis
  consumer:
    build:
      context: ./src
      dockerfile: ../consumer.dockerfile
    entrypoint: 'celery -A test worker --loglevel INFO -c 4'
    volumes:
      - logs:/var/log
    networks:
      - redis
    cap_add:
      - SYS_PTRACE

networks:
  redis:

volumes:
  redis:
  logs:
    driver_opts:
      type: none
      o: bind
      device: /var/log
